<!DOCTYPE html>
<html>
	<head>
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <meta name="author" content="Robson Ponti">
	    
	    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="css/styles.css">
		<link rel="stylesheet" type="text/css" href="css/core.css">
		<link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;700&display=swap" rel="stylesheet">

		<link rel="stylesheet" type="text/css" href="css/components.css">

		<title>Eat Tasty - App</title>

	</head>
		<body>
<header>
	<div class="header-wrapper">


		<div class="menu-right">
			<ul>
				<li><a href="javascript:void(0);" class="account-link"><i class="far fa-user"></i></a></li>
				<li><a href="javascript:void(0);"><i class="far fa-heart"></i><span class="favorite-count">0</span></a></li>
				<li><a href="javascript:void(0);" onclick="cart.show();"><i class="fas fa-shopping-cart"></i><span class="cart-count"><?=$this->cart_info()["items"]?></span></a></li>
			</ul>
		</div>



<!--LOGIN/REGISTER-->
	<div class="header-account-holder">
		<span class="close-account-button"><i class="fa fa-times"></i></span>
		<div class="form">
			<div class="form-tab">
				<button class="btn active" tab="login">Login</button>
				<button class="btn" tab="register">Registar</button>
			</div>

			<!--LOGIN-->
				<div id="login" class="form-item active">
					<form action="#" method="post">
						<div class="form-row">
							<label for="username">Utilizador ou email&nbsp;<span class="required">*</span></label>
							<input type="text" name="username" id="username" autocomplete="username" value="">
						</div>
						<div class="form-row">
							<label for="password">Palavra-passe&nbsp;<span class="required">*</span></label>
							<input type="text" name="password" id="password" autocomplete="username" value="">
						</div>
						<div class="form-row">
							<label for="keeploged"><input type="checkbox" name="keeploged" id="keeploged"><span>Lembrar-me</span></label>
							<label class="login-button"><button class="btn btn-dark-red">Login</button></label>
							<a href="#" class="forgot-link">Esqueci Password</a>
						</div>
					</form>
				</div>
			<!--//LOGIN-->


			<!--LOGIN-->
				<div id="register" class="form-item">
					<form action="#" method="post">
						<div class="form-row">
							<label for="username">Email&nbsp;<span class="required">*</span></label>
							<input type="text" name="username" id="username" autocomplete="username" value="">
						</div>
						<div class="form-row">
							<label for="password">Palavra-passe&nbsp;<span class="required">*</span></label>
							<input type="text" name="password" id="password" autocomplete="username" value="">
						</div>
						<div class="form-row">
							<label class="privacy-warning">Os seus dados pessoais serão usados para apoiar a sua experiência neste site, para gerir o acesso à sua conta e para outros fins descritos na nossa <strong>política de privacidade</strong>.</label>
							<label for="agree-register"><input type="checkbox" name="agree-register" id="agree-register"><span>Concordo</span></label>
							<label class="register-button"><button class="btn btn-dark-red disabled" disabled>Registar</button></label>

						</div>
					</form>
				</div>
			<!--//LOGIN-->


		</div>

	</div>	

<!--//LOGIN/REGISTER//-->



<!--CART ITEMS-->
	<div class="header-cart-holder">
		<span class="close-cart-button" onclick="cart.close();"><i class="fa fa-times"></i></span>
			<div class="cart-header">
				<h1>Itens no Cesto</h1>
			</div>
			<div id="cart-list-items">
			<?=$this->cart()?>
			</div>

	</div>
<!--//CART ITEMS//-->


	</div><!--header wrapper-->



</header>
			<main>
				



				<?=$this->Render() 
				?>
			
			</main>


			<!--SCRIPTS-->
    		<script src="https://kit.fontawesome.com/8e63e58d24.js" crossorigin="anonymous"></script>
			<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
			<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
			<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
			<!--//SCRIPTS-->

			<script src="js/app.js"></script>
		</body>
</html>

