<div id="login">    
    <div class="wrapper vh-100">
      <div class="row align-items-center h-100">
        <form action="login/check" method="post" class="col-lg-3 col-md-4 col-10 mx-auto text-center">
          <div class="form-group">
            <label for="inputEmail" class="sr-only">Email address</label>
            <input type="email" name="username" id="inputEmail" value="admin" class="form-control form-control-lg required" placeholder="Utilizador" autofocus="">
          </div>
          <div class="form-group">
            <label for="inputPassword" class="sr-only">Password</label>
            <input type="password" name="password" id="inputPassword" value="admin" class="form-control form-control-lg required" placeholder="Palavra-Passe">
          </div>
          <button class="btn btn-lg btn-primary btn-block" id="doLogin">Login</button>
          <span id="msg"></span>
        </form>
      </div>
    </div>
</div>